// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4A4Zg0PJIdtr-Lvw8Oc5MCS4DIj3Tr1g',
    appId: '1:878687993489:web:2a3816bc4cad01a07a0930',
    messagingSenderId: '878687993489',
    projectId: 'reservations-app-5f3fe',
    authDomain: 'reservations-app-5f3fe.firebaseapp.com',
    storageBucket: 'reservations-app-5f3fe.appspot.com',
    measurementId: 'G-XEJZQGNZNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaycqcPUfhoAQu57B-S0jAd4WmyOruepg',
    appId: '1:878687993489:android:4910469e2ee33c9c7a0930',
    messagingSenderId: '878687993489',
    projectId: 'reservations-app-5f3fe',
    storageBucket: 'reservations-app-5f3fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxHUHDijkXer_tR2EIpD8eppwJXCAkIWg',
    appId: '1:878687993489:ios:b59a6a27b4ce33f67a0930',
    messagingSenderId: '878687993489',
    projectId: 'reservations-app-5f3fe',
    storageBucket: 'reservations-app-5f3fe.appspot.com',
    iosClientId: '878687993489-u82kpregrqbd2ek6o3rnrc2ep4vm9pic.apps.googleusercontent.com',
    iosBundleId: 'com.example.reservationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxHUHDijkXer_tR2EIpD8eppwJXCAkIWg',
    appId: '1:878687993489:ios:b59a6a27b4ce33f67a0930',
    messagingSenderId: '878687993489',
    projectId: 'reservations-app-5f3fe',
    storageBucket: 'reservations-app-5f3fe.appspot.com',
    iosClientId: '878687993489-u82kpregrqbd2ek6o3rnrc2ep4vm9pic.apps.googleusercontent.com',
    iosBundleId: 'com.example.reservationsApp',
  );
}
